In [2]:
#搜尋值
import pandas as pd
dataFrame1 = pd.read_csv('學生成績表1.csv')
dataFrame1.index = dataFrame1['姓名']
dataFrame2 = dataFrame1.drop(columns='姓名')
dataFrame2

      國文   英文  數學   地理   歷史   總分    平均    排名
姓名
程玫靖   73   88  90   99   84  434  86.8   1.0
李慶亮   84   98  97   89   53  421  84.2   2.0
黃詩妃   68   97  76   93   86  420  84.0   3.0
吳欣書   95   92  86   91   55  419  83.8   4.0
林佳光   55   85  98   97   77  412  82.4   5.0
黃健發   55   84  98   86   87  410  82.0   6.0
吳淑惠   84   87  96   69   73  409  81.8   7.0
謝貞妃   62   67  98   98   81  406  81.2   8.0
魏秋萍   79  100  71   92   64  406  81.2   8.0
張伊映   98   64  82   80   81  405  81.0  10.0
陳淑娟   58  100  90   80   71  399  79.8  11.0
藍哲嘉   84   51  99  100   65  399  79.8  11.0
陳倩妮   61   71  95   73   97  397  79.4  13.0
陳向愛  100   96  56   51   90  393  78.6  14.0
溫重意   97   88  68   53   87  393  78.6  14.0
藍哲嘉   68   74  91   73   85  391  78.2  16.0
戴萱能   70   97  70   50  100  387  77.4  17.0
陳淑娟   95   51  60   93   88  387  77.4  17.0
林珍旺   53   82  72   79  100  386  77.2  19.0
張俊傑   71   78  66   94   75  384  76.8  20.0
劉嘉泰   96   57  55   71   95  374  74.8  21.0
游倫城   71   90  60   71   81  373  74.6  22.0
鍾俞禎   58   97  50   85   83  373  74.6  22.0
魏秋萍   65   91  64   72   79  371  74.2  24.0
張嘉韋   62   95  71   56   79  363  72.6  25.0
鄭奇翰   73   66  75   62   87  363  72.6  25.0
呂傑宣   85   52  77   64   82  360  72.0  27.0
張凱妮   93   93  55   60   59  360  72.0  27.0
高智超   65   65  81   69   79  359  71.8  29.0
王雅慧   50   76  97   57   79  359  71.8  29.0
謝哲維   68   66  73   76   74  357  71.4  31.0
彭茹靖   87   93  53   66   58  357  71.4  31.0
艾巧夫  100   68  61   61   66  356  71.2  33.0
趙偉銘   86   82  58   56   71  353  70.6  34.0
黃嘉琪   58   60  89   69   76  352  70.4  35.0
吳麗卿   58   94  55   72   72  351  70.2  36.0
葉志峰   67   61  73   82   64  347  69.4  37.0
楊綺芬   95   85  59   50   57  346  69.2  38.0
李政成   66   64  95   60   57  342  68.4  39.0
鄭奇翰   80   57  85   56   63  341  68.2  40.0
吳志宣   79   74  70   62   55  340  68.0  41.0
王雅慧   77   67  79   61   55  339  67.8  42.0
郭淑真   67   78  64   68   60  337  67.4  43.0
王泓泰   56   55  84   72   66  333  66.6  44.0
馬彥文   59   71  85   53   65  333  66.6  44.0
張明惟   58   61  60   60   93  332  66.4  46.0
林向鈺   72   80  69   53   55  329  65.8  47.0
張牧聿   58   52  66   61   89  326  65.2  48.0
溫重意   57   50  58   91   57  313  62.6  49.0
郎慧萍   65   51  50   62   83  311  62.2  50.0

In [5]:
import pandas as pd
dataFrame1 = pd.read_csv('學生成績表1.csv')
dataFrame1.index = dataFrame1['姓名']
dataFrame2 = dataFrame1.drop(columns='姓名')
dataFrame2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 程玫靖 to 郎慧萍
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   國文      50 non-null     int64
 1   英文      50 non-null     int64
 2   數學      50 non-null     int64
 3   地理      50 non-null     int64
 4   歷史      50 non-null     int64
 5   總分      50 non-null     int64
 6   平均      50 non-null     float64
 7   排名      50 non-null     float64
dtypes: float64(2), int64(6)
memory usage: 3.5+ KB

In [3]:
dataFrame2['國文'] < 60

姓名
程玫靖    False
李慶亮    False
黃詩妃    False
吳欣書    False
林佳光     True
黃健發     True
吳淑惠    False
謝貞妃    False
魏秋萍    False
張伊映    False
陳淑娟     True
藍哲嘉    False
陳倩妮    False
陳向愛    False
溫重意    False
藍哲嘉    False
戴萱能    False
陳淑娟    False
林珍旺     True
張俊傑    False
劉嘉泰    False
游倫城    False
鍾俞禎     True
魏秋萍    False
張嘉韋    False
鄭奇翰    False
呂傑宣    False
張凱妮    False
高智超    False
王雅慧     True
謝哲維    False
彭茹靖    False
艾巧夫    False
趙偉銘    False
黃嘉琪     True
吳麗卿     True
葉志峰    False
楊綺芬    False
李政成    False
鄭奇翰    False
吳志宣    False
王雅慧    False
郭淑真    False
王泓泰     True
馬彥文     True
張明惟     True
林向鈺    False
張牧聿     True
溫重意     True
郎慧萍    False
Name: 國文, dtype: bool

In [4]:
#國文成績不及格的,subscript
dataFrame2[dataFrame2['國文'] < 60]

     國文   英文  數學  地理   歷史   總分    平均    排名
姓名
林佳光  55   85  98  97   77  412  82.4   5.0
黃健發  55   84  98  86   87  410  82.0   6.0
陳淑娟  58  100  90  80   71  399  79.8  11.0
林珍旺  53   82  72  79  100  386  77.2  19.0
鍾俞禎  58   97  50  85   83  373  74.6  22.0
王雅慧  50   76  97  57   79  359  71.8  29.0
黃嘉琪  58   60  89  69   76  352  70.4  35.0
吳麗卿  58   94  55  72   72  351  70.2  36.0
王泓泰  56   55  84  72   66  333  66.6  44.0
馬彥文  59   71  85  53   65  333  66.6  44.0
張明惟  58   61  60  60   93  332  66.4  46.0
張牧聿  58   52  66  61   89  326  65.2  48.0
溫重意  57   50  58  91   57  313  62.6  49.0

In [12]:
#國文成績不及格的,使用query
dataFrame2.query('國文<60')

     國文   英文  數學  地理   歷史   總分    平均    排名
姓名
林佳光  55   85  98  97   77  412  82.4   5.0
黃健發  55   84  98  86   87  410  82.0   6.0
陳淑娟  58  100  90  80   71  399  79.8  11.0
林珍旺  53   82  72  79  100  386  77.2  19.0
鍾俞禎  58   97  50  85   83  373  74.6  22.0
王雅慧  50   76  97  57   79  359  71.8  29.0
黃嘉琪  58   60  89  69   76  352  70.4  35.0
吳麗卿  58   94  55  72   72  351  70.2  36.0
王泓泰  56   55  84  72   66  333  66.6  44.0
馬彥文  59   71  85  53   65  333  66.6  44.0
張明惟  58   61  60  60   93  332  66.4  46.0
張牧聿  58   52  66  61   89  326  65.2  48.0
溫重意  57   50  58  91   57  313  62.6  49.0

In [8]:
#國文成績或者英文不及格的,subscript
dataFrame2[(dataFrame2['國文'] < 60) | (dataFrame2['英文'] < 60)]

     國文   英文  數學   地理   歷史   總分    平均    排名
姓名
林佳光  55   85  98   97   77  412  82.4   5.0
黃健發  55   84  98   86   87  410  82.0   6.0
陳淑娟  58  100  90   80   71  399  79.8  11.0
藍哲嘉  84   51  99  100   65  399  79.8  11.0
陳淑娟  95   51  60   93   88  387  77.4  17.0
林珍旺  53   82  72   79  100  386  77.2  19.0
劉嘉泰  96   57  55   71   95  374  74.8  21.0
鍾俞禎  58   97  50   85   83  373  74.6  22.0
呂傑宣  85   52  77   64   82  360  72.0  27.0
王雅慧  50   76  97   57   79  359  71.8  29.0
黃嘉琪  58   60  89   69   76  352  70.4  35.0
吳麗卿  58   94  55   72   72  351  70.2  36.0
鄭奇翰  80   57  85   56   63  341  68.2  40.0
王泓泰  56   55  84   72   66  333  66.6  44.0
馬彥文  59   71  85   53   65  333  66.6  44.0
張明惟  58   61  60   60   93  332  66.4  46.0
張牧聿  58   52  66   61   89  326  65.2  48.0
溫重意  57   50  58   91   57  313  62.6  49.0
郎慧萍  65   51  50   62   83  311  62.2  50.0

In [9]:
#國文成績和英文同時不及格的,subscript
dataFrame2[(dataFrame2['國文'] < 60) & (dataFrame2['英文'] < 60)]

     國文  英文  數學  地理  歷史   總分    平均    排名
姓名
王泓泰  56  55  84  72  66  333  66.6  44.0
張牧聿  58  52  66  61  89  326  65.2  48.0
溫重意  57  50  58  91  57  313  62.6  49.0

In [10]:
#國文成績或者英文不及格的,query()
dataFrame2.query('國文<60' or '英文<60')

     國文   英文  數學  地理   歷史   總分    平均    排名
姓名
林佳光  55   85  98  97   77  412  82.4   5.0
黃健發  55   84  98  86   87  410  82.0   6.0
陳淑娟  58  100  90  80   71  399  79.8  11.0
林珍旺  53   82  72  79  100  386  77.2  19.0
鍾俞禎  58   97  50  85   83  373  74.6  22.0
王雅慧  50   76  97  57   79  359  71.8  29.0
黃嘉琪  58   60  89  69   76  352  70.4  35.0
吳麗卿  58   94  55  72   72  351  70.2  36.0
王泓泰  56   55  84  72   66  333  66.6  44.0
馬彥文  59   71  85  53   65  333  66.6  44.0
張明惟  58   61  60  60   93  332  66.4  46.0
張牧聿  58   52  66  61   89  326  65.2  48.0
溫重意  57   50  58  91   57  313  62.6  49.0

In [11]:
#國文成績和英文同時不及格的,query()
dataFrame2.query('國文<60' and '英文<60')

     國文  英文  數學   地理  歷史   總分    平均    排名
姓名
藍哲嘉  84  51  99  100  65  399  79.8  11.0
陳淑娟  95  51  60   93  88  387  77.4  17.0
劉嘉泰  96  57  55   71  95  374  74.8  21.0
呂傑宣  85  52  77   64  82  360  72.0  27.0
鄭奇翰  80  57  85   56  63  341  68.2  40.0
王泓泰  56  55  84   72  66  333  66.6  44.0
張牧聿  58  52  66   61  89  326  65.2  48.0
溫重意  57  50  58   91  57  313  62.6  49.0
郎慧萍  65  51  50   62  83  311  62.2  50.0